<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\TrojanRequestBlocker\Plugin;

use MagedIn\TrojanRequestBlocker\Service\Validator\FakeUserRegistration;
use Magento\Checkout\Api\PaymentInformationManagementInterface;
use Magento\Quote\Api\Data\PaymentInterface;
use Magento\Quote\Api\Data\AddressInterface;
use Magento\Framework\Exception\LocalizedException;
use Magento\Store\Model\StoreManagerInterface;

/**
 * Plugin to validate registered customer checkout information
 */
class RegisteredCustomerCheckout
{
    /**
     * @var FakeUserRegistration
     */
    private FakeUserRegistration $validator;

    /**
     * @var StoreManagerInterface
     */
    private StoreManagerInterface $storeManager;

    /**
     * @param FakeUserRegistration $validator
     * @param StoreManagerInterface $storeManager
     */
    public function __construct(
        FakeUserRegistration $validator,
        StoreManagerInterface $storeManager
    ) {
        $this->validator = $validator;
        $this->storeManager = $storeManager;
    }

    /**
     * Before plugin for savePaymentInformationAndPlaceOrder method
     *
     * @param PaymentInformationManagementInterface $subject
     * @param int $cartId
     * @param PaymentInterface $paymentMethod
     * @param AddressInterface|null $billingAddress
     * @return array
     * @throws LocalizedException
     */
    public function beforeSavePaymentInformationAndPlaceOrder(
        PaymentInformationManagementInterface $subject,
        $cartId,
        PaymentInterface $paymentMethod,
        AddressInterface $billingAddress = null
    ): array {
        $store = $this->storeManager->getStore();
        
        if ($billingAddress) {
            // For registered customers, we only validate the billing address information
            // since the email is already associated with their account
            $this->validator->validate(
                $billingAddress->getEmail() ?: 'registered@customer.com', // Fallback email
                $billingAddress->getFirstname(),
                $billingAddress->getLastname(),
                \Magento\Store\Model\ScopeInterface::SCOPE_STORE,
                $store->getId()
            );
        }

        return [$cartId, $paymentMethod, $billingAddress];
    }

    /**
     * Before plugin for savePaymentInformation method
     *
     * @param PaymentInformationManagementInterface $subject
     * @param int $cartId
     * @param PaymentInterface $paymentMethod
     * @param AddressInterface|null $billingAddress
     * @return array
     * @throws LocalizedException
     */
    public function beforeSavePaymentInformation(
        PaymentInformationManagementInterface $subject,
        $cartId,
        PaymentInterface $paymentMethod,
        AddressInterface $billingAddress = null
    ): array {
        $store = $this->storeManager->getStore();
        
        if ($billingAddress) {
            // For registered customers, we only validate the billing address information
            // since the email is already associated with their account
            $this->validator->validate(
                $billingAddress->getEmail() ?: 'registered@customer.com', // Fallback email
                $billingAddress->getFirstname(),
                $billingAddress->getLastname(),
                \Magento\Store\Model\ScopeInterface::SCOPE_STORE,
                $store->getId()
            );
        }

        return [$cartId, $paymentMethod, $billingAddress];
    }
}
